# Generated by Django 5.2.8 on 2026-02-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_property',
            field=models.ForeignKey(blank=True, help_text='For Staff: Which specific property do they work at?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='property.property'),
        ),
    ]
