from django.db import models
from django.conf import settings
from users.models import Organization
# Ideally use fernet_fields for encryption, but using CharField for simplicity now. 
# In prod, recommend django-fernet-fields.

# --- NEW: SAAS PAYMENT CONFIGURATION ---
class PaymentConfiguration(models.Model):
    """
    Stores the Agency's specific Paybill credentials.
    Money goes directly to them.
    """
    organization = models.OneToOneField(Organization, on_delete=models.CASCADE, related_name='payment_config')
    paybill_number = models.CharField(max_length=20)
    
    # Store these securely! (In a real app, use EncryptedCharField)
    consumer_key = models.CharField(max_length=255, help_text="Daraja Consumer Key")
    consumer_secret = models.CharField(max_length=255, help_text="Daraja Consumer Secret")
    business_shortcode = models.CharField(max_length=20, help_text="Shortcode/Paybill")
    passkey = models.CharField(max_length=255, help_text="Lipa na M-Pesa Passkey", blank=True, null=True)
    
    is_configured = models.BooleanField(default=False)

    def __str__(self):
        return f"Payment Config for {self.organization.name}"

# --- NEW: SOFTWARE INVOICE (Billing the Agency) ---
class SoftwareInvoice(models.Model):
    """
    Bills generated by YOU (Luxia) sent to the AGENCY (Organization).
    """
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='software_invoices')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=255) # e.g. "Integration Fee" or "March Subscription"
    date_issued = models.DateField(auto_now_add=True)
    due_date = models.DateField()
    is_paid = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.organization.name} - {self.amount} ({'Paid' if self.is_paid else 'Due'})"

# --- 1. Property Structure (Existing) ---

class Property(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    blocks = models.CharField(max_length=255, help_text="Comma-separated blocks, e.g., 'Tower A, Tower B'", blank=True)
    
    # NEW: Default Utility Rates for this Property
    water_unit_cost = models.DecimalField(max_digits=10, decimal_places=2, default=150.00, help_text="Cost per cubic meter")
    electricity_unit_cost = models.DecimalField(max_digits=10, decimal_places=2, default=25.00, help_text="Cost per unit (if sub-metered)")

    def __str__(self):
        return f"{self.name} ({self.organization.name})"
    
    @property
    def total_units_count(self): return self.unit_set.count()
    @property
    def occupied_units_count(self): return self.unit_set.filter(current_tenant__isnull=False).count()
    class Meta: verbose_name_plural = "Properties"

# --- Staff Assignment Model (Existing) ---
class PropertyStaff(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='staff_assignment')
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='staff_members')
    
    def __str__(self):
        return f"{self.user.username} -> {self.property.name}"

class Unit(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    block = models.CharField(max_length=50, blank=True)
    floor = models.CharField(max_length=10)
    door_number = models.CharField(max_length=10)
    unit_number = models.CharField(max_length=20, editable=False)
    is_locked = models.BooleanField(default=False)
    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='owned_units')
    organization_owner = models.ForeignKey(Organization, on_delete=models.SET_NULL, null=True, blank=True)
    current_tenant = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='occupied_unit')

    def save(self, *args, **kwargs):
        prefix = f"{self.block}-" if self.block else ""
        self.unit_number = f"{prefix}{self.floor}{self.door_number}"
        super().save(*args, **kwargs)

    def __str__(self): return f"{self.property.name} - {self.unit_number}"
    class Meta: unique_together = ('property', 'block', 'floor', 'door_number')

# --- 2. Visitor & Short Term (Existing) ---
class VisitorLog(models.Model):
    VISITOR_TYPES = [('DELIVERY', 'Delivery'), ('SERVICE', 'Service'), ('SOCIAL', 'Social Visit'), ('TAXI', 'Taxi')]
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='visitors')
    visitor_name = models.CharField(max_length=100)
    visitor_id_number = models.CharField(max_length=50, blank=True, null=True)
    visitor_phone = models.CharField(max_length=20, blank=True, null=True)
    id_collected_at_gate = models.BooleanField(default=False)
    visitor_type = models.CharField(max_length=20, choices=VISITOR_TYPES, default='SOCIAL')
    notified_tenant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    entry_time = models.DateTimeField(auto_now_add=True)
    exit_time = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    allowed_entry = models.BooleanField(default=False)
    notes = models.CharField(max_length=255, blank=True)

class ShortTermStay(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='short_term_stays')
    guest_name = models.CharField(max_length=255)
    guest_id_number = models.CharField(max_length=50)
    guest_phone = models.CharField(max_length=20, blank=True, null=True)
    id_passport_image = models.ImageField(upload_to='guest_ids/%Y/%m/', blank=True, null=True)
    check_in_time = models.DateTimeField(auto_now_add=True)
    checked_in_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='stays_checked_in')
    check_out_time = models.DateTimeField(null=True, blank=True)
    checked_out_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='stays_checked_out')
    is_active = models.BooleanField(default=True)
    feedback_rating = models.IntegerField(null=True, blank=True)
    feedback_comment = models.TextField(blank=True, null=True)

# --- 3. Financials & Operations (Enhanced) ---

class Invoice(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='invoices')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    due_date = models.DateField()
    is_paid = models.BooleanField(default=False)
    description = models.CharField(max_length=200)
    sender_role = models.CharField(max_length=20, default='ORGANIZATION')
    mpesa_code = models.CharField(max_length=50, null=True, blank=True)
    checkout_request_id = models.CharField(max_length=100, blank=True, null=True, help_text="M-Pesa Transaction ID for tracking callbacks")
    payment_date = models.DateTimeField(null=True, blank=True)
    
    def __str__(self): return f"Invoice #{self.id} - {self.unit.unit_number} - {self.amount}"

# --- NEW: UTILITY METERING ---
class Meter(models.Model):
    """Physical meter attached to a unit."""
    METER_TYPES = [('WATER', 'Water'), ('ELEC', 'Electricity')]
    unit = models.OneToOneField(Unit, on_delete=models.CASCADE, related_name='meter')
    meter_number = models.CharField(max_length=50, help_text="Serial Number")
    meter_type = models.CharField(max_length=10, choices=METER_TYPES, default='WATER')
    
    def __str__(self): return f"{self.meter_type} Meter - {self.unit.unit_number}"

class MeterReading(models.Model):
    """Monthly readings log."""
    meter = models.ForeignKey(Meter, on_delete=models.CASCADE, related_name='readings')
    date_recorded = models.DateField(auto_now_add=True)
    previous_reading = models.DecimalField(max_digits=10, decimal_places=2)
    current_reading = models.DecimalField(max_digits=10, decimal_places=2)
    consumption = models.DecimalField(max_digits=10, decimal_places=2, help_text="Units Used")
    bill_amount = models.DecimalField(max_digits=10, decimal_places=2)
    
    # Evidence
    reading_image = models.ImageField(upload_to='meter_readings/%Y/%m/', blank=True, null=True)
    recorded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    
    # Link to the generated invoice
    invoice = models.OneToOneField(Invoice, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        # Auto-calculate consumption
        self.consumption = self.current_reading - self.previous_reading
        super().save(*args, **kwargs)

# --- NEW: EXPENSE TRACKING ---
class ExpenseCategory(models.Model):
    """Standard categories (e.g. Repairs, Salaries, KPLC)"""
    name = models.CharField(max_length=100)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE) # Categories can be Org-specific
    
    def __str__(self): return self.name
    class Meta: verbose_name_plural = "Expense Categories"

class Expense(models.Model):
    """Digital Petty Cash Record"""
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='expenses')
    category = models.ForeignKey(ExpenseCategory, on_delete=models.SET_NULL, null=True)
    payee = models.CharField(max_length=100, help_text="Who was paid? (e.g. KPLC, Juma)")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_incurred = models.DateField()
    description = models.TextField(blank=True)
    receipt_image = models.ImageField(upload_to='expenses/%Y/%m/', blank=True, null=True)
    recorded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    
    def __str__(self): return f"{self.amount} - {self.payee} ({self.date_incurred})"

class Ticket(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    submitted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    priority = models.CharField(max_length=10, default='MEDIUM')
    status = models.CharField(max_length=20, default='OPEN')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    assigned_to = models.CharField(max_length=100, blank=True, null=True)

class Notification(models.Model):
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_notifications')
    message = models.TextField()
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='sent_notifications')
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

class Announcement(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='announcements')
    title = models.CharField(max_length=200)
    content = models.TextField()
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

class ParkingLot(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    lot_number = models.CharField(max_length=10)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'role':'HO'}, related_name='owned_parking_lots')
    current_tenant = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'role': 'T'}, related_name='assigned_parking_lot')