# Generated by Django 5.2.8 on 2025-11-25 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'T'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='current_tenant',
            field=models.OneToOneField(blank=True, help_text='The Tenant currently assigned this lot by the owner.', limit_choices_to={'userprofile__role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parking_lot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The Home Owner/Landlord who owns this parking lot.', limit_choices_to={'userprofile__role': 'HO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parking_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(help_text='The management company overseeing this property.', on_delete=django.db.models.deletion.CASCADE, to='property.organization'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='unit',
            name='current_tenant',
            field=models.OneToOneField(blank=True, help_text='The tenant currently leasing this unit.', limit_choices_to={'userprofile__role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_unit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'HO'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AlterUniqueTogether(
            name='parkinglot',
            unique_together={('property', 'lot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
    ]
