# Generated by Django 5.2.8 on 2026-02-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'T'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='current_tenant',
            field=models.OneToOneField(blank=True, limit_choices_to={'userprofile__role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parking_lot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'HO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parking_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.organization'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='property.property'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='current_tenant',
            field=models.OneToOneField(blank=True, limit_choices_to={'userprofile__role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_unit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization_owner',
            field=models.ForeignKey(blank=True, help_text='Used if the unit is owned directly by the management company/organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.organization'),
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'HO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='property.unit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='property.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='parkinglot',
            unique_together={('property', 'lot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
    ]
