# Generated by Django 5.2.8 on 2025-11-26 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='current_tenant',
            field=models.OneToOneField(blank=True, limit_choices_to={'userprofile__role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parking_lot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'HO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parking_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.organization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='current_tenant',
            field=models.OneToOneField(blank=True, limit_choices_to={'userprofile__role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_unit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('description', models.CharField(default='Monthly Service Charge', max_length=200)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='property.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Name of technician or staff assigned.', max_length=100, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='property.unit')),
            ],
        ),
    ]
