# Generated by Django 5.2.8 on 2026-02-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'HO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parking_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='current_tenant',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parking_lot', to=settings.AUTH_USER_MODEL),
        ),
    ]
