# Generated by Django 5.2.8 on 2026-02-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_parkinglot_owner_alter_parkinglot_current_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa Transaction ID for tracking callbacks', max_length=100, null=True),
        ),
    ]
