# Generated by Django 5.2.8 on 2025-12-10 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_notification_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='organization_owner',
            field=models.ForeignKey(blank=True, help_text='Used if the unit is owned directly by the management company/organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.organization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'HO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
