# Generated by Django 5.2.8 on 2026-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_unit_organization_owner_alter_unit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
